services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql 
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodeapp
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network      
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 15s
      retries: 10

  nginx:
    image: nginx:latest
    container_name: nginx
    build: 
      context: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - node-network

  app:
    build: 
      context: node-app
    container_name: app
    volumes:
      - ./node-app/app-data:/app
      - /app/node_modules
    tty: true
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - node-network

networks:
  node-network:
    driver: bridge